apiVersion: v1
kind: Pod
metadata:
 name: configmap-secret-volume
spec:
 containers:
 - name: ip-app-cm-secret-vol
   image: kvriyaa/ip_app:4
   imagePullPolicy: Always
   ports:
   - containerPort: 80
   volumeMounts:
   - name: cm-volume
     mountPath: "/app/volume/configmap"
   - name: secret-volume
     mountPath: "/app/volume/secret"
 volumes:
 - name: cm-volume
   configMap:
    name: my-config-prop
 - name: secret-volume
   secret:
    secretName: secret-as-vol
