apiVersion: v1
kind: Pod
metadata:
  name:  emptydir-demo2
spec:
 containers:
 - name: nginx
   image: nginx:latest
   ports:
   - containerPort: 80
   volumeMounts:
     - name: shared-volume2
       mountPath: "/var/log/nginx/"
 - name: busybox
   image: busybox
   command: ["bin/sh"]
   args: ["-c", "while true; do ls /var/log/nginx; cat /var/log/nginx/access.log; sleep 5; done"]
   volumeMounts:
   - name: shared-volume2
     mountPath: "/var/log/nginx/"
 volumes:
 - name: shared-volume2
   emptyDir: {}
