apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: kavi
spec:
  selector:
    app: my-app
  ports:
    - port: 32500
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: kavi
spec:
  selector:
    app: my-app
  ports:
    - port: 32500  # ❌ Conflict: Same `port` as `service-a`
      targetPort: 8080

