apiVersion: v1
kind: Service
metadata:
 name: new-app-with-clusterip
spec:
 type: ClusterIP
 selector:
  name: new-app
 ports:
  - name: http
    port: 30001
    targetPort: 80

---


apiVersion: apps/v1
kind: Deployment
metadata:
 name: multi-clusterpod
spec:
 replicas: 2
 selector:
  matchLabels: 
   name: new-app
 template:
  metadata:
   labels:
    name: new-app
  spec:
   containers:
   - name: my-ip-app
     image: kvriyaa/ip-app:4
     imagePullPolicy: Always
     ports:
     - containerPort: 80
   - name: my-busybox
     image: busybox
     command: ["sh", "-c", " echo Hello from Busy box"]




    
  


  
 
