apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-secret
  template:
    metadata:
      labels:
        app: my-app-secret
    spec:
      containers:
      - name: my-sample
        image: kvriyaa/pri-ip-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-secret-pri 
        

