apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-secret
  template:
    metadata:
      labels:
        app: my-app-secret
    spec:
      containers:
      - name: my-sample
        image: kvriyaa/sample_img:alpinev1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        

