apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment-secretk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-secretk
  template:
    metadata:
      labels:
        app: my-app-secretk
    spec:
      containers:
      - name: my-sample
        image: kvriyaa/pri-ip-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: kavi-secret-pri 
        

