apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
 name: service-account-role-binding
subjects:
- kind: ServiceAccount
  name: my-sa-sample
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: pod-service-role-sample
