apiVersion: v1
kind: Service
metadata:
 name: my-clusterip
spec:
 type: ClusterIP
 selector:
  app: my-app1
 ports:
  - name: http
    port: 30002
    targetPort: 80
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment-clusterip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
      - name: my-ip-app
        image: kvriyaa/ip_app:4
        imagePullPolicy: Always
        ports:
        - containerPort: 80





