apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
 name: service-account-role-binding-cluster
subjects:
- kind: ServiceAccount
  name: my-sa-cluster
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: pod-service-role-sample-cluster
