apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole  
metadata:
  name: pod-service-role-sample-cluster
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list", "delete"]
