apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-with-policy
spec:
 storageClassName: local
 accessModes:
 - ReadWriteMany
 resources:
  requests:
   storage: 1Gi
 volumeName: my-pv-with-policy 
