apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-50gi
spec:
  storageClassName: local
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  hostPath:
    path: '/home/ubuntu/'
