apiVersion: v1
kind: Service
metadata:
 name: my-nodeport2
spec:
 type: NodePort
 selector:
  app: my-app-node2
 ports:
  - name: http
    nodePort: 31100
    port: 31000
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment-nodeport2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app1-node2
  template:
    metadata:
      labels:
        app: my-app1-node2
    spec:
      containers:
      - name: my-ip-app-node2
        image: kvriyaa/ip_app:4
        imagePullPolicy: Always
        ports:
        - containerPort: 80

