apiVersion: v1
kind: Pod
metadata:
  name: my-pvc-volume
spec:
  containers:
  - name: ip-app
    image: kvriyaa/ip_app:4
    ports:
    - containerPort: 80
    volumeMounts:
    - name: my-pvc-mount
      mountPath: /app/pvc-volume
  volumes: 
  - name: my-pvc-mount
    persistentVolumeClaim:
        claimName: my-pvc
